name: Publish Maven Package

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para escribir en GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'
          cache: 'maven'
          # Esta línea configura el settings.xml automáticamente para GitHub Packages:
          server-id: github
          settings-path: ${{ github.workspace }}

#      - name: Publish to GitHub Packages
#        run: mvn clean deploy -DskipTests
#        env:
#          # Estas variables de entorno alimentan directamente al servidor 'github' del settings.xml
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          USERNAME: ${{ github.actor }}
#          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Search JAR
        run: cd ./commons.utils/target/*.jar

#      - name: Upload JAR Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: commons-utils-jar
#          path: commons.utils/target/*.jar